name: CI Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build CPU image
        run: |
          docker build \
          --target ci \
          --build-arg TARGET=ci \
          --build-arg TORCH_VERSION=2.5.1+cpu \
          --build-arg TORCH_INDEX_URL=https://download.pytorch.org/whl/cpu \
          -t transformer-ci .
      - name: Run Docker container
        run: |
          docker run --rm \
          -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} \
          transformer-ci
          
      # Tests are disabled
      # - name: Run tests
      #   run: |
      #     docker run --rm \
      #     -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} \
      #     transformer-ci \
      #     pytest -m "not gpu" /transformer-architectures/tests